{{- if .Values.persistence.mappings.enabled }}
{{- /* https://kubernetes.io/docs/concepts/storage/persistent-volumes/#writing-portable-configuration */}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wiremock.fullname" . }}-mappings-data
  labels:
    {{- include "wiremock.labels" . | nindent 4 }}
spec:
  {{- with .Values.persistence.mappings.accessModes }}
  accessModes: {{ . | toYaml | nindent 2 }}
  {{- end }}
  {{- /* https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1 */}}
  {{- with .Values.persistence.mappings.storageClassName }}
  storageClassName: {{ ternary "" . (eq `-` .) | quote }}
  {{- end }}
  resources:
    requests:
      storage: "{{ .Values.persistence.mappings.size }}"
{{- end }}
